---
title: "Analysis - raw vals test6"
author: "Paloma"
date: "`r Sys.Date()`"
output: workflowr::wflow_html
editor_options: 
  chunk_output_type: console
---
# Introduction

```{r}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r libraries, echo = FALSE, warning = FALSE, message=FALSE}
# Install libraries
library(knitr)
library(RColorBrewer)
library(stats)
library(coefplot)
library(arm)
library(bbmle)
library(plyr)
library(dplyr)
library(ggpmisc)
library(ggplot2)
```

```{r loading}
# loading info
# Loading data
data <- read.csv("./data/Test6/Data_QC_flagged.csv")
std <- read.csv("./data/Test6/Standard_data_test6.csv")
cort_valsA<- read.csv("./data/Test5/Data_cort_values_methodA.csv")
cort_valsB<- read.csv("./data/Test5/Data_cort_values_methodB.csv")

# remove NSB
data <- data[!(data$Sample == "NSB"),]

#Inclusion of standard readings in plot
data1 <- data[,c("Sample","Wells", "Category", "CategoryB", "Binding.Perc", "Ave_Conc_pg.ml", "Weight_mg", "Buffer_nl", "Spike", "Conc_pg.ml", "CV.Perc", "Dilution_sample")]
std1 <- std[,c("Sample", "Wells", "Category", "Binding.Perc", "Backfit")]
#std1$Binding.Perc <- std1$Binding.Perc*100
std1$Spike <- NA
std1$Buffer_nl <- NA
std1$Category <- "Standard"
std1$Weight_mg <- NA
colnames(std1)[5]<- c("Ave_Conc_pg.ml")

data_std <- join(data1, std1, type = "full") 

```

# Summary of results (all experiments)

```{r exp.binding.perc, fig.width=7, fig.height=6}
# Scatter plot of Experiment A and B, observed binding % 

ggplot(data_std, aes(x = log(Ave_Conc_pg.ml), 
                 y = Binding.Perc, color = Category)) +

  geom_point(size = 2) +
  geom_text(aes(label = Sample), size = 3, vjust = -1, hjust = 0.5, color = "gray30") +
  geom_hline(yintercept = 80, linetype = "dashed", 
             color = "gray", linewidth = 1) +  
  geom_hline(yintercept = 20, linetype = "dashed", 
             color = "gray", linewidth = 1) +  # Add horizontal line 
 # stat_poly_eq(aes(x = Sample_num, label = paste(..rr.label.., sep = "~")),
  #             formula = y ~ x, parse = TRUE, size = 2.5) +
 # geom_abline(slope = 14.72, intercept = -3.6, linetype = "dashed", color = "lightblue") + # ideal line
  labs(title = "Observed binding %",
       subtitle = "",
       x = "log(concentration), pg/mL", y = "Binding Percentage") +
  scale_y_continuous(n.breaks = 10) + 
  theme_minimal() 

```

```{r}
a <- filter(data_std, Category == "Standard" | CategoryB  == "A" | CategoryB  == "A-SP" | CategoryB == "Pool" , !is.na(Binding.Perc)) 

a$Weight_mg[is.na(a$Weight_mg)] <- "Standard"
a$CategoryB[is.na(a$CategoryB )] <- "Standard"

a$Weight_tag <- ifelse(a$Weight_mg == 15, "15mg", 
                       ifelse(a$Weight_mg == 20, "20mg", 
                              "Standard"))
a_sub<-subset(a, a$Category == "Standard")
ggplot(a, aes(x = log(Ave_Conc_pg.ml), 
              y = Binding.Perc, 
                color = CategoryB, 
                shape = factor(Weight_tag))) +
  geom_smooth(data = a_sub,
               se = FALSE,
               linewidth = 0.2, 
               alpha = 0.1) +
  geom_text(aes(label = Sample), size = 3, vjust = -1, hjust = 0.5, color = "gray50") +
  geom_point(size = 2) +
  geom_hline(yintercept = 80, linetype = "dashed", 
             color = "gray", linewidth = 0.5) +  
  geom_hline(yintercept = 20, linetype = "dashed", 
             color = "gray", linewidth = 0.5) +  # Add horizontal line 
 # stat_poly_eq(aes(x = Sample_num, label = paste(..rr.label.., sep = "~")),
  #             formula = y ~ x, parse = TRUE, size = 2.5) +
 # geom_abline(slope = 14.72, intercept = -3.6, linetype = "dashed", color = "lightblue") + # ideal line
  labs(title = "Observed binding % for A",
       subtitle = "",
       x = "Sample", y = "Binding Percentage") +
  scale_y_continuous(n.breaks = 10) + 
  theme_minimal() 

```



```{r}
a<-data_std
a <- filter(data_std, !is.na(Binding.Perc)) 
#a <- a %>%
 # filter(!Sample %in% c("B0", "BE", "NSB"))
a$Sample_num <- 1:length(a$Sample)


ggplot(a, aes(x = Binding.Perc, 
              y = CV.Perc, 
                color = Category,
                shape =  as.factor(Weight_mg))) +
  geom_point(size = 2) +
  geom_text(aes(label = Sample), size = 3, vjust = -1, hjust = 0.5, color = "gray30") +
  geom_vline(xintercept = 80, linetype = "dashed", 
             color = "gray", linewidth = 1) +  
  geom_vline(xintercept = 20, linetype = "dashed", 
             color = "gray", linewidth = 1) +  
  geom_hline(yintercept = 10, linetype = "dashed", 
             color = "firebrick", linewidth = 0.5) +  
  labs(title = "Binding and CV limits",
       subtitle = "Complete dataset",
       x = "Binding %", y = "CV %") +
  scale_y_continuous(n.breaks = 10) + 
  theme_minimal() 

```


```{r expABCD.conc.expect.vs.observed}
#a <- filter(data_std, Category == "A" | Category =="Standard" | Category == "B" | Category == "C" | Category == "D", !is.na(Binding.Perc)) 
a$Sample_num <- 1:length(a$Sample)

a$Exp <- NA

ggplot(a, aes(x = Exp, 
                 y = (Ave_Conc_pg.ml), color = Category)) +
  geom_smooth(method = "lm", se = FALSE, linewidth = 0.5, alpha = 0.06) +
  geom_point(size = 2) +
  geom_text(aes(label = Sample), size = 3, vjust = -1, hjust = 0.5, color = "gray50") +
  stat_poly_eq(aes(x = Exp, label = paste(..rr.label.., sep = "~~~")),
               formula = y ~ x, parse = TRUE, size = 4) +
   geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "gray") +
  labs(title = "All serial dilutions: expected vs observed cortisol concentrations",
       subtitle = "Complete dataset",
       x = "Expected vals (pg/mL)", y = "Observed vals (pg/mL)") +
  theme_bw() 

``` 

## Experiment A: normal sample dilution

```{r expA.binding.perc}
# Scatter plot of Experiment A, observed binding % by category
a <- filter(data_std, Category == "Parallelism" | Category == "Parallelism-SP" | Category =="Standard", !is.na(Binding.Perc)) 
a$Sample_num <- 1:length(a$Sample)

ggplot(a, aes(x = Sample_num, 
                 y = Binding.Perc, color = Category)) +
  geom_smooth(method = "lm", se = TRUE, linewidth = 0.5, alpha = 0.2) +
  geom_point(size = 2) +
  geom_text(aes(label = Sample), size = 3, vjust = -1, hjust = 0.5, color = "gray30") +
  geom_hline(yintercept = 80, linetype = "dashed", 
             color = "gray", linewidth = 1) +  
  geom_hline(yintercept = 20, linetype = "dashed", 
             color = "gray", linewidth = 1) +  # Add horizontal line 
#  stat_poly_eq(aes(x = Sample_num, label = paste(..rr.label.., sep = "~~~")),
 #              formula = y ~ x, parse = TRUE, size = 4) +
 # geom_abline(slope = 14.72, intercept = -3.6, linetype = "dashed", color = "lightblue") + # ideal line
  labs(title = "Observed binding % of Serial dilutions and Standard",
       subtitle = "20 mg, TF = Non-Spiked, TG = Spiked",
       x = "Sample", y = "Binding Percentage") +
  scale_y_continuous(n.breaks = 10) + 
  theme_minimal() 

```




