---
title: "About"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---
## Background
This document provides an overview of the ELISA protocol employed to measure cortisol concentrations in hair samples. Hair cortisol is a valuable biomarker for long-term stress exposure, offering insights into chronic physiological stress. This protocol was tested with different sample masses and dilutions to optimize accuracy for low-weight samples.

## Objectives
The goal of this protocol is to accurately quantify hair cortisol concentrations and validate the effectiveness of Nist et al. 2020 method for measuring physiological stress. The following analyses document each step from sample preparation to data processing and statistical modeling.

## Strategy 
All samples in this essay were obtained from the same person, and were extracted using the same protocol. The parameters that we want to optimize vary for different samples:

- The buffer volume for the reconstitution
- The weight of each sample
- Addition (or not) of a spike using same dilution as for STD 1.


## Sample Preparation
1. **Hair Collection**: Hair samples are collected from participants and stored in a cool, dry environment until processing.
2. **Sample Processing**: Each sample is washed, dried, and ground into a fine powder to ensure homogeneity.
3. **Cortisol Extraction**: Cortisol is extracted using methanol, following standard lab procedures to ensure consistent recovery.

## ELISA Protocol Summary 

The ELISA assay is run on a microplate using a cortisol-specific antibody. After incubation, absorbance readings are measured, and cortisol concentrations are calculated using a standard curve. Samples are prepared in multiple formats:

### ASSAY 3
- **Spiked Samples**: 25 µL of a known cortisol standard is added to 25 uL of sample.
- **Non-Spiked Samples**: 50 µL of unaltered sample for actual measurement.
- **Dilution**: reconstitution using 60 uL, or using 250 uL
- **Weight**: varies between 11 and 37.1 mg (mean=23.22)

### ASSAY 4
- **Spiked Samples**:
- **Non-Spiked Samples**: 
- **Dilution**:
- **Weight**: 


The output from the plate reader, as well as all the information to interpret it, are stored in this repository. We used the original output from Myassays as it provides a better fitting curve than one calculated manually.
For further details on calculations used in these analyses, refer to the links in the Home page.


