---
title: "Analysis - raw vals test9"
author: "Paloma"
date: "`r Sys.Date()`"
output: workflowr::wflow_html
editor_options: 
  chunk_output_type: console
---
# Introduction

```{r}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r libraries, echo = FALSE, warning = FALSE, message=FALSE}
# Install libraries
library(knitr)
library(RColorBrewer)
library(stats)
library(coefplot)
library(arm)
library(bbmle)
library(plyr)
library(ggpmisc)
library(ggplot2)
library(dplyr)
```

```{r loading}

# Loading data
data_path <- "./data/Test9"
cat("Input:")
print(file.path(data_path, "Data_QC_flagged.csv"))  # Check the full path
print(file.path(data_path, "Data_cort_values.csv"))  # 
std <- read.csv(file.path(data_path, "Standard_data_test251008.csv"))
data <- read.csv(file.path(data_path, "Data_QC_flagged.csv"))

#Inclusion of standard readings in plot

std$Spike <- NA
std$Buffer_nl <- NA
std$Order <- 25
std$Weight_mg <- NA
std$Sample<-gsub("Standard", "std", std$Sample)
std <- dplyr::rename(std, Conc_pg.ml = Backfit)

data_std <- join(std, data, by = "Wells", type = "full")

data_std <- data_std[order(data_std$Order), ]

```

# Summary of results 
## Binding Percentage by groups

```{r groups.binding.perc, fig.width=7, fig.height=6}
# Scatter plot  observed binding % 


ggplot(data_std, aes(x = 1:nrow(data_std), 
                 y = Binding.Perc, color = Category)) +
  geom_smooth(method = "lm", se = FALSE, linewidth = 0.2, linetype = 2, alpha = 0.2, aes(group = Category)) +
  geom_point(size = 2) +
  geom_text(aes(label = Sample), size = 3, vjust = -1, hjust = 0.5, color = "gray30") +
  geom_hline(yintercept = 80, linetype = "dashed", 
             color = "gray", linewidth = 1) +  
  geom_hline(yintercept = 20, linetype = "dashed", 
             color = "gray", linewidth = 1) +  # Add horizontal line 
 # stat_poly_eq(aes(x = Sample_num, label = paste(..rr.label.., sep = "~")),
  #             formula = y ~ x, parse = TRUE, size = 2.5) +
 # geom_abline(slope = 14.72, intercept = -3.6, linetype = "dashed", color = "lightblue") + # ideal line
  labs(title = "Observed binding %",
       subtitle = "",
       x = "", y = "% Binding") +
  scale_y_continuous(n.breaks = 10) + 
#  xlim(0,25) +
  theme_minimal() 

```



```{r groups.binding.perc.cort, fig.width=7, fig.height=6}
# Scatter plot observed binding % and cort vals

ggplot(data_std, aes(x = log(Ave_Conc_pg.ml), 
                 y = Binding.Perc, color = Category)) +
  geom_smooth(method = "lm", se = FALSE, linewidth = 0.2, linetype = 2, alpha = 0.2, aes(group = Category)) +
  geom_jitter(size = 2) +
  geom_text(aes(label = Sample), size = 3, vjust = -1, hjust = 0.5, color = "gray30") +
  geom_hline(yintercept = 80, linetype = "dashed", 
             color = "gray", linewidth = 1) +  
  geom_hline(yintercept = 20, linetype = "dashed", 
             color = "gray", linewidth = 1) +   
  labs(title = "Observed binding % and cortisol values",
       subtitle = "cort vals not controlling for differences in weight or reconstitution volume",
       x = "Log Concentration (pg/mg)", y = "Binding Percentage") +
  scale_y_continuous(n.breaks = 10) + 
  theme_minimal()

```

```{r groups.binding.perc.cort.zoom.in, fig.width=7, fig.height=6}
# Scatter plot observed binding % and cort vals

ggplot(data_std, aes(x = Ave_Conc_pg.ml, 
                 y = Binding.Perc, color = Category)) +
  geom_point(size = 2) +
 # xlim(0,8500) +
  geom_text(aes(label = Sample), size = 3, vjust = -1, hjust = 0.5, color = "gray30") +
  geom_smooth( method = "gam", formula = y ~ s(log(x)), se = FALSE, linewidth = 0.5, alpha = 0.1) +
  geom_hline(yintercept = 80, linetype = "dashed", 
             color = "gray", linewidth = 1) +  
  geom_hline(yintercept = 20, linetype = "dashed", 
             color = "gray", linewidth = 1) +   
  labs(title = "Observed binding % and cortisol values, excluding outliers",
       subtitle = "cort vals not controlling for differences in weight or reconstitution volume",
       x = "Concentration (pg/mg)", y = "Binding Percentage") +
  scale_y_continuous(n.breaks = 10) + 
  theme_minimal() 

```

## Binding by sample

```{r expA.binding.perc}
# Scatter plot of Experiment A, observed binding % by category
a <- filter(data_std, Category == "Spike" | Category == "Std" | Category == "P10-noSP" | Category == "PC-SP", !is.na(Binding.Perc))
a$Sample_num <- 1:length(a$Sample)


ggplot(a, aes(x = Sample_num, 
                 y = Binding.Perc, color = Category)) +
  geom_smooth(method = "lm", se = TRUE, linewidth = 0.5, alpha = 0.1) +
    geom_errorbar(aes(ymin = Binding.Perc - SD, ymax = Binding.Perc + SD, color = Category, alpha = 0.05)) +
  geom_point(size = 2) +
  geom_text(aes(label = Sample), size = 3, vjust = -1, hjust = 0.5, color = "gray30") +
  geom_hline(yintercept = 80, linetype = "dashed", 
             color = "gray", linewidth = 1) +  
  geom_hline(yintercept = 20, linetype = "dashed", 
             color = "gray", linewidth = 1) +  # Add horizontal line 
#  stat_poly_eq(aes(x = Sample_num, label = paste(..rr.label.., sep = "~~~")),
 #              formula = y ~ x, parse = TRUE, size = 4) +
 # geom_abline(slope = 14.72, intercept = -3.6, linetype = "dashed", color = "lightblue") + # ideal line
  labs(title = "Observed binding %",
       subtitle = "",
       x = "Sample", y = "Binding Percentage") +
  scale_y_continuous(n.breaks = 10, limits = c(0,100)) + 
  theme_minimal() 

```



