---
title: "ELISA_Visualizations"
author: "Paloma"
date: "2024-10-16"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# Introduction

```{r echo = FALSE, warning = FALSE, message=FALSE}
# Install libraries
library(dplyr)
library(knitr)
library(ggplot2)
library(RColorBrewer)
```

```{r }

# load dataset
data <- read.csv("./data/Data_QC_filtered.csv")

#  since Buffer and spike are not continuous variables, change from numeric to factors
data$Buffer_nl <- as.factor(data$Buffer_nl)
data$Spike <- as.factor(data$Spike)

```

## Calculating deviation from 50% binding
```{r}

data$Binding_deviation <- abs(data$Binding.Perc - 50)
sorted_data <- data[order(data$Binding_deviation), ]

dim(sorted_data)
# View top results (closest to 50% Binding Percentage)
kable(sorted_data)

```

# Scatterplots 

### Binding percentage
```{r}

# Scatter plot of Binding Percentage vs Weight, 4 groups
ggplot(data, aes(x = Weight_mg, y = Binding.Perc, color = factor(Spike), shape = factor(Buffer_nl))) +
  geom_point(size = 3) +
  geom_smooth(method = "lm", se = FALSE, linewidth = 0.5) +  # Add a linear trend line
  labs(title = "Binding Percentage vs Weight, 4 groups",
       x = "Weight (mg)", y = "Binding Percentage") +
   scale_y_continuous(n.breaks = 10) +  
    geom_hline(yintercept = 50, linetype = "dashed", color = "gray", linewidth = 1) +  # Add horizontal line at y = 20
  theme_minimal()
 

# Scatter plot of Binding Percentage vs Weight, 2 groups (Buffer)
ggplot(data, aes(x = Weight_mg, y = Binding.Perc, color = factor(Buffer_nl))) +
  geom_point(size = 3) +
  geom_smooth(method = "lm", se = FALSE, linewidth = 0.5) +  # Add a linear trend line
  labs(title = "Binding Percentage vs Weight, by Buffer",
       x = "Weight (mg)", y = "Binding Percentage") +
   scale_y_continuous(n.breaks = 10) +  
    geom_hline(yintercept = 50, linetype = "dashed", color = "gray", linewidth = 1) +  # Add horizontal line at y = 20
  theme_minimal()


# Scatter plot of Binding Percentage vs Weight, 2 groups (Spike)
ggplot(data, aes(x = Weight_mg, y = Binding.Perc, shape = factor(Spike))) +
  geom_point(size = 3, colour = "cyan4") +
  geom_smooth(method = "lm", se = FALSE, linewidth = 0.5, colour = "cyan3") +  # Add a linear trend line
  labs(title = "Binding Percentage vs Weight, by Spike",
       x = "Weight (mg)", y = "Binding Percentage") +
   scale_y_continuous(n.breaks = 10) +  
    geom_hline(yintercept = 50, linetype = "dashed", color = "gray", linewidth = 1) +  # Add horizontal line at y = 20
  theme_minimal()


```

### Coef. of variation percentage

```{r}
# Scatterplot of CV Percentage vs Buffer & Spike
ggplot(data, aes(x = factor(Buffer_nl), y = CV.Perc, fill = factor(Spike))) +
  geom_boxplot() +
  labs(title = "Coef. of variation by Buffer and Spike",
       x = "Buffer (nl)", y = "Coef of variation %") +
   scale_y_continuous(n.breaks = 10) +  
  theme_minimal()


# Scatter plot of Binding Percentage vs Weight, 4 groups
ggplot(data, aes(x = Weight_mg, y = CV.Perc, color = factor(Spike), shape = factor(Buffer_nl))) +
  geom_point(size = 3) +
  geom_smooth(method = "lm", se = FALSE, linewidth = 0.5) +  # Add a linear trend line
  labs(title = "Coef. of variation vs Weight, 4 groups",
       x = "Weight (mg)", y = "Coef of variation %") +
   scale_y_continuous(n.breaks = 10) +  
  theme_minimal()
 
```


### Deviation from 50% binding

```{r}

# Scatter plot of Binding Deviation vs Weight, 4 groups
ggplot(data, aes(x = Weight_mg, y = Binding_deviation, color = factor(Spike), shape = factor(Buffer_nl))) +
  geom_point(size = 3) +
  geom_smooth(method = "lm", se = FALSE, linewidth = 0.5) +  # Add a linear trend line
  labs(title = "Binding Deviation vs Weight, 4 groups",
       x = "Weight (mg)", y = "Binding Deviation") +
   scale_y_continuous(n.breaks = 10) +  
  theme_minimal()

# Scatter plot of Binding Deviation vs Weight, colored by Buffer
ggplot(data, aes(x = Weight_mg, y = Binding_deviation, color = factor(Buffer_nl))) +
  geom_point(size = 3) +
  geom_smooth(method = "lm", se = FALSE) +  # Add a linear trend line
  labs(title = "Binding Deviation vs Weight, colored by Buffer",
       x = "Weight (mg)", y = "Binding Percentage") +
   scale_y_continuous(n.breaks = 10) +  
  theme_minimal()

# Scatter plot of Binding Deviation vs Weight, shape by Spike
ggplot(data, aes(x = Weight_mg, y = Binding_deviation, shape = factor(Spike))) +
  geom_point(size = 3, colour = "cyan4") + 
  geom_smooth(method = "lm", se = FALSE, linewidth = 0.5, colour = "cyan3") +  # Add a linear trend line
  labs(title = "Binding Deviation vs Weight, shape by Spike",
       x = "Weight (mg)", y = "Binding Deviation") +
   scale_y_continuous(n.breaks = 10) +  
  theme_minimal()

```

# Boxplots

### Binding percentage
```{r}

# Boxplot of Binding Percentage vs Buffer & Spike
ggplot(data, aes(x = factor(Buffer_nl), y = Binding.Perc, fill = factor(Spike))) +
  geom_boxplot() +
  labs(title = "Binding Percentage by Buffer and Spike",
       x = "Buffer (nl)", y = "Binding Percentage") +
   scale_y_continuous(n.breaks = 10) +  
      geom_hline(yintercept = 50, linetype = "dashed", color = "gray", linewidth = 1) + 
  theme_minimal()


# Boxplot of Binding Percentage vs Buffer
ggplot(data, aes(x = factor(Buffer_nl), y = Binding.Perc, fill = factor(Buffer_nl))) +
  geom_boxplot() +
  labs(title = "Binding Percentage by Buffer",
       x = "Buffer (nl)", y = "Bindings Percentage") +
   scale_y_continuous(n.breaks = 10) +  
      geom_hline(yintercept = 50, linetype = "dashed", color = "gray", linewidth = 1) + 
  theme_minimal()

# Boxplot of Binding Percentage vs Spike
ggplot(data, aes(x = factor(Spike), y = Binding.Perc, fill = Spike)) +
  geom_boxplot() +
  labs(title = "Binding Percentage by Spike",
       x = "Spike", y = "Binding Percentage") +
   scale_y_continuous(n.breaks = 10) +  
   geom_hline(yintercept = 50, linetype = "dashed", color = "gray", linewidth = 1) +
  theme_minimal()

```

### Coef. of variation percentage

```{r}


# Boxplot of CV Percentage vs Buffer & Spike
ggplot(data, aes(x = factor(Buffer_nl), y = CV.Perc, fill = factor(Spike))) +
  geom_boxplot() +
  labs(title = "Coef. of variation by Buffer and Spike",
       x = "Buffer (nl)", y = "Coef of variation %") +
   scale_y_continuous(n.breaks = 10) +  
  theme_minimal()

```



### Deviation from 50% binding
```{r}

# Box plot to visualize distribution of Binding deviation by Buffer and Spike
ggplot(data, aes(x = factor(Buffer_nl), y = Binding_deviation, fill = factor(Spike))) +
  geom_boxplot() +
  labs(title = "Binding deviation by Buffer and Spike",
       x = "Buffer (nl)", y = "Binding deviation") +
   scale_y_continuous(n.breaks = 10) +  
  theme_minimal()




```

 wflow_publish("./analysis/ELISA_visualizations.Rmd")


