---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

## Evaluation of Nist et al. 2020

This protocol is different from others in that it should make possible to quantify cortisol in low-mass hair samples (i.e. less than 20 mg). The study conducted by Nist et al. quantifies cortisol in hair samples form neonates, but to our knowledge, it has not been tested with low-mass adult samples.

The increased sensibility of Nist et al. 2020 is provided by two modifications in the traditional protocol:
 
- extraction using methanol is conducted twice
- a spike of a known amount of cortisol is added

I tested this protocol by running an ELISA plate with 40 samples from one adult individual. In order to find optimal parameters for my adult samples, I tested different mass, dilution, and the addition (or not) of a spike. 

The results suggest that the method proposed by Nist et al. 2020 does not produce reliable results, and does not allow us to quantify cortisol from adult hair. However, **it remains a question if using lower-mass samples would result in accurate results** (more testing forthcoming). 

Among the non-spiked samples, and using a double extraction, we found that a dilution of 250 uL, and using between 20 to 35 mg of hair provides the most consistent results. 

This is how data is obtained: 


    |-- Plate reader produces optical density (OD) values
             |
             |
             |---> Myassays.com uses ODs and map of plate layout to:
                  1) Subtract readings for the NSB (non-specific binding) well 
                  (0% binding) from all values
                  2) Normalize values dividing by reading for zero standard 
                  (blank, or B0)
                  3) Fit a 4-Parameter Logistic curve (for a sigmoidal shape) 
                  to the standard readings
                  4) Extrapolate cortisol concentration values from the curve
                        * Obtained values for each replicate separately by 
                        treating them as a single sample when providing 
                        the plate layout
                        * These values do not control for differences 
                        in dilution, sample weight, spike, etc. 
                        * Values obtained are in the same unit as the
                        standards provided (pg/ml)
                              |
                              |
                              |------> In R I calculate final values using the formula:
                              
                              A / B x C / D x E 
                                          ▪	A = output myassays.com (pg/ml)
                                          ▪	B = sample mass (mg)
                                          ▪	C = methanol added for extraction (mL)
                                          ▪	D = methanol recovered (mL)
                                          ▪	E = reconstitution volume (mL)

                              
File with complete dataset has the following columns for each single data point:

-	Plate_num
-	Well (character)
-	Sample (character)
-	Category (character)
- Subcategory (character)
- Person
- Order
- Num_strands
-	Weight_mg (numeric)
-	Reconst_buffer_ml (numeric) - reconstitution volume
- Sample_well_ml (numeric)
-	Buffer_well_ml (numeric) - if added to well
-	Buffer_tube_ml (numeric) - if added to tube
-	Dilution_factor_sample (numeric) - if diluted
-	Spike (numeric) - 0 for no, or 1 for yes
-	Spike_well_ml (numeric) - vol of spike if added to well
-	Spike_tube_ml (numeric) - vol of spike if added to tube
-	Dilution_factor_spike (1 if std1, 4 if std 4; not diluted before adding to well)
-	Extraction_ratio (numeric) - methanol added / methanol recovered
- OD
- Binding_perc
- Conc_pg_ml
- Ave_conc_pg_ml
- Final_pg_ml
- CV_perc
- Quality
-	Comments (character)



                        

Find more details in the pages below:

- [Background information and experimental design](https://palomacontreras25.github.io/HairCort-Evaluation-Nist2020/docs/about.html)


**Plate overall description**

| Test # |  Date    | Report | Data | Observations|
|---|----|----|-----|-----------------|
|   10   | 10-09-25 | [Plate10](https://palomacontreras25.github.io/HairCort-Evaluation-Nist2020/output/Test10/Test10_plate_report.html)  | [Results 10](https://palomacontreras25.github.io/HairCort-Evaluation-Nist2020/data/Test10/Merged_ELISA_results_T10.csv)   |NA |
|   9    | 10-08-25 | [Plate9](https://palomacontreras25.github.io/HairCort-Evaluation-Nist2020/output/Test9/Test9_plate_report.html) | [Results 9](https://palomacontreras25.github.io/HairCort-Evaluation-Nist2020/data/Test9/Merged_ELISA_results_T9.csv)  | Used multichannel, slower dispensing but worked well overall   |
|   8    | 09-02-25 | [Plate8](https://palomacontreras25.github.io/HairCort-Evaluation-Nist2020/output/Test8/Test8_plate_report.html)  | [Results 8](https://palomacontreras25.github.io/HairCort-Evaluation-Nist2020/data/Test8/Merged_ELISA_results_T8.csv)| Plate washer overflowed, washed twice  |
|   7    | 08-10-25 | [Plate7](https://palomacontreras25.github.io/HairCort-Evaluation-Nist2020/output/Test7/Test7_plate_report.html)  | [Results 7](https://palomacontreras25.github.io/HairCort-Evaluation-Nist2020/data/Test7/Merged_ELISA_results_T7.csv)|Had issues with repeater: addition of conjugate and antibody was not homogeneous (particularly the antibody) |
|   6    | 05-30-25 | | |  Did not use results. Plate broke, individual wells got disorganized, not sure if put it back in the right order    |
|   5    | 05-13-25 | | | Mistake: added TMB before washing plate. Washed the plate and added TMB again. Overall, it seems like values are smaller than in previous plates. Also, Tina's samples were much more pulverized than mine    |
|   4    | 02-19-25 |    | |             |
|   3    | 09-15-24 |      | |           |

